_target_: instant_avatar.datasets.custom.CustomDataModule
name: andy
subject: andy
gender: neutral
opt:
  dataroot: ./data/custom/${dataset.subject}/
  subject: ${dataset.subject}
  train:
    num_workers: 8
    batch_size: 1
    start: 1
    end: 168
    skip: 1
    downscale: 1
    sampler: ${sampler}
    fitting: ${model.opt.optimize_SMPL.enable}
    refine: ${model.opt.optimize_SMPL.is_refine}
  val:
    num_workers: 4
    batch_size: 1
    start: 167
    end: 168
    skip: 5
    downscale: 1
  test:
    num_workers: 4
    batch_size: 1
    start: 167
    end: 168
    skip: 5
    downscale: 1
